#
# Copyright (c) 2008-2019 the Urho3D project.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

version: '{build}'
image: Visual Studio 2019
platform:
  - x86
  - x64
clone_depth: 50
cache:
  # Cache the MinGW compiler toolchains so that our CI builds do not chalk up their download stats
  - C:\tools\mingw32
  - C:\tools\mingw64
environment:
  GIT_NAME:
    secure: rUVYYb1+C4EI2xAlvF4pEA==
  GIT_EMAIL:
    secure: ls0sOtf/IGC0qWsktlmJxEJT+MTUPF2lGg6zq0FBES0=
  GH_TOKEN:
    secure: bqIoUQDNTAO0jqmKFjpqH7JZxcS5MmBuGFUxy7rzOMQ4zABe21p8Hrd+EOL29kn/
# VS build actually does not need MinGW compiler toolchains so prevent its restoration and update check
  APPVEYOR_CACHE_SKIP_RESTORE: true
  APPVEYOR_CACHE_SKIP_SAVE: true
  TOOLSET: host=x64
  config: Release
# We cannot afford to have a large matrix on AppVeyor at the moment
  URHO3D_D3D11: 1
  URHO3D_LUAJIT: 1
  matrix:
    - URHO3D_LIB_TYPE: STATIC
    - URHO3D_LIB_TYPE: SHARED
before_build:
  - rake ci_timer
  - ps: if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:COMMIT_MESSAGE = $(git log --format=%B -n 1 $env:APPVEYOR_REPO_COMMIT) };
        if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:RELEASE_TAG = $env:APPVEYOR_REPO_TAG_NAME };
        $env:URHO3D_TOOLS = "0";
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - if "%PLATFORM%" == "x64" (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" &&
      set "URHO3D_64BIT=1"
    ) else (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
    )
build_script:
  - rake ci && if "%PACKAGE_UPLOAD%" == "1" rake ci_package_upload
  - rake ci_timer
test: off
deploy: off

# vi: set ts=2 sw=2 expandtab:
