# Copyright (c) 2008-2022 the Urho3D project
# License: MIT

---

name: Website event dispatcher
on:
  push:
    branches: [ master ]
jobs:
  dispatch:
    name: Dispatch build event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: What changed
        id: whatchanged
        run: |
          git fetch --deepen=1
          echo ::set-output name=skip::$(git log --raw --no-merges -1 |grep -cq 'website/'; echo $?)
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.DISPATCHER_TOKEN }}
          repository: weitjong/urho3d-website
          event-type: build
          client-payload: '{"sha": "${{ github.sha }}"}'
        if: steps.whatchanged.outputs.skip == '0'

...

# vi: set ts=2 sw=2 expandtab:
